//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoQuyCa
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public string UserName { get; set; }
        public System.DateTime ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public double TienMat_DauCa { get; set; }
        public double TienThuTrongCa { get; set; }
        public double TienBanGiaoLai { get; set; }
        public double TienMat_CuoiCa { get; set; }
        public double TongTienHang { get; set; }
        public double TongTienCK { get; set; }
        public double TongTienThue { get; set; }
        public double TongTienCKToanHD { get; set; }
        public double TongTienPhaiThanhToan { get; set; }
        public double TongTienDaThu { get; set; }
        public double DaThu_TienMat { get; set; }
        public double DaThu_TienGui { get; set; }
        public double DaThu_TheGiamGia { get; set; }
        public double DaThu_TheGiaTri { get; set; }
        public double DaThu_DiemTichLuy { get; set; }
        public double TongTienDoiTraLai { get; set; }
        public double TongTienThucTe { get; set; }
        public double ConThieu { get; set; }
        public bool DaKetThucCa { get; set; }
    }
}
