//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BH_MuaHang
    {
        public BH_MuaHang()
        {
            this.BH_MuaHang_ChiTiet = new HashSet<BH_MuaHang_ChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string SoChungTu { get; set; }
        public System.DateTime NgayChungTu { get; set; }
        public Nullable<System.Guid> ID_DoiTuong { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public Nullable<System.Guid> ID_DonMuaHang { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public string NguoiGiao { get; set; }
        public double TyGia { get; set; }
        public string DienGiai { get; set; }
        public double TongTienHang { get; set; }
        public double TongTienThue { get; set; }
        public double TongPhaiTra { get; set; }
        public double TongChiPhi { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public double TongChietKhau { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public string UserLap { get; set; }
        public string UserSuaCuoi { get; set; }
    
        public virtual BH_DonMuaHang BH_DonMuaHang { get; set; }
        public virtual ICollection<BH_MuaHang_ChiTiet> BH_MuaHang_ChiTiet { get; set; }
        public virtual DM_DoiTuong DM_DoiTuong { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
    }
}
