//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinhHomThu
    {
        public System.Guid ID { get; set; }
        public string DiaChiEmail { get; set; }
        public string MatKhau { get; set; }
        public string UserSoHuu { get; set; }
        public string MayChu_Gui { get; set; }
        public Nullable<int> Cong_Gui { get; set; }
        public Nullable<bool> SSL_Gui { get; set; }
        public string MayChu_Nhan { get; set; }
        public Nullable<int> Cong_Nhan { get; set; }
        public Nullable<bool> SSL_Nhan { get; set; }
    }
}
