//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHBangLuongTheoMucDoanhThu
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> BoPhan { get; set; }
        public double DoanhSo_Min { get; set; }
        public Nullable<double> DoanhSo_Max { get; set; }
        public bool LaThoChinh { get; set; }
        public double LuongDuocNhan { get; set; }
        public bool LuongTheoPT { get; set; }
        public System.DateTime TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    }
}
