//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHGiamTruBangLuong
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_BoPhanTra { get; set; }
        public bool LaThoChinh { get; set; }
        public System.Guid ID_BoPhanNhan { get; set; }
        public double LuongGiamTru { get; set; }
        public bool LaPhanTram { get; set; }
        public System.DateTime TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    }
}
