//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChietKhauMacDinh_NhanVien
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ID_SanPham { get; set; }
        public Nullable<System.Guid> NhanVien { get; set; }
        public double ChietKhau { get; set; }
        public bool LaPhanTram { get; set; }
        public Nullable<System.Guid> ID_NhomNhanVien { get; set; }
        public bool TheoNhomNhanVien { get; set; }
        public Nullable<System.Guid> ID_NhomHangHoa { get; set; }
        public bool TheoNhomHangHoa { get; set; }
        public Nullable<double> ChietKhau_YeuCau { get; set; }
        public Nullable<bool> LaPhanTram_YeuCau { get; set; }
        public Nullable<bool> ChietKhauTuVan { get; set; }
    
        public virtual DM_HangHoa DM_HangHoa { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_NhomHangHoa DM_NhomHangHoa { get; set; }
    }
}
