//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongDoan_DichVu
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_DichVu { get; set; }
        public int STT { get; set; }
        public System.Guid ID_CongDoan { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<double> SoPhutThucHien { get; set; }
    }
}
