//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachThi
    {
        public System.Guid ID { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public System.Guid ID_MonThi { get; set; }
        public Nullable<System.Guid> ID_GiaoVien { get; set; }
        public Nullable<System.Guid> ID_TrongTai { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
