//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieuChuyenKho
    {
        public DieuChuyenKho()
        {
            this.DieuChuyenKho_ChiTiet = new HashSet<DieuChuyenKho_ChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaChungTu { get; set; }
        public System.DateTime NgayDieuChuyen { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public double TyGia { get; set; }
        public double TongTien { get; set; }
        public string GhiChu { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public string UserLap { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_LoaiDieuChuyen { get; set; }
        public Nullable<bool> DaDuyet { get; set; }
    
        public virtual ICollection<DieuChuyenKho_ChiTiet> DieuChuyenKho_ChiTiet { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
    }
}
