//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DoiTuong
    {
        public DM_DoiTuong()
        {
            this.BH_DonBanHang = new HashSet<BH_DonBanHang>();
            this.BH_DonMuaHang = new HashSet<BH_DonMuaHang>();
            this.BH_MuaHang = new HashSet<BH_MuaHang>();
            this.CongNoDauKis = new HashSet<CongNoDauKi>();
            this.DM_HangHoa = new HashSet<DM_HangHoa>();
            this.DM_LienHe = new HashSet<DM_LienHe>();
            this.HangDoiTraLais = new HashSet<HangDoiTraLai>();
            this.HangTraLaiNhaCungCaps = new HashSet<HangTraLaiNhaCungCap>();
            this.HoaDonBans = new HashSet<HoaDonBan>();
            this.HoaDonBanLes = new HashSet<HoaDonBanLe>();
            this.KH_Anh = new HashSet<KH_Anh>();
            this.KH_NhapKho = new HashSet<KH_NhapKho>();
            this.KH_XuatKho = new HashSet<KH_XuatKho>();
            this.PhieuChiChiTiets = new HashSet<PhieuChiChiTiet>();
            this.PhieuThuChiTiets = new HashSet<PhieuThuChiTiet>();
            this.TheKhachHangs = new HashSet<TheKhachHang>();
            this.TinNhans = new HashSet<TinNhan>();
        }
    
        public System.Guid ID { get; set; }
        public int LoaiDoiTuong { get; set; }
        public bool LaCaNhan { get; set; }
        public Nullable<System.Guid> ID_NhomDoiTuong { get; set; }
        public string MaDoiTuong { get; set; }
        public string TenDoiTuong { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public byte[] Anh { get; set; }
        public string MaSoThue { get; set; }
        public string TaiKhoanNganHang { get; set; }
        public Nullable<double> GioiHanCongNo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> ID_TinhThanh { get; set; }
        public Nullable<System.DateTime> NgaySinh_NgayTLap { get; set; }
        public bool ChiaSe { get; set; }
        public bool TheoDoi { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<bool> TheoDoiVanTay { get; set; }
        public Nullable<int> ID_Index { get; set; }
        public Nullable<System.Guid> ID_QuanHuyen { get; set; }
        public Nullable<System.Guid> ID_NhanVienPhuTrach { get; set; }
        public Nullable<System.DateTime> NgayDoiNhom { get; set; }
        public Nullable<double> DiemKhoiTao { get; set; }
        public Nullable<double> DoanhSoKhoiTao { get; set; }
        public Nullable<System.Guid> ID_NguoiGioiThieu { get; set; }
        public Nullable<System.Guid> ID_NguonKhach { get; set; }
        public string CapTai_DKKD { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> GioiTinhNam { get; set; }
        public string NganHang { get; set; }
        public Nullable<System.DateTime> NgayCapCMTND_DKKD { get; set; }
        public string NoiCapCMTND_DKKD { get; set; }
        public string SDT_CoQuan { get; set; }
        public string SDT_NhaRieng { get; set; }
        public string SoCMTND_DKKD { get; set; }
        public string ThuongTru { get; set; }
        public string XungHo { get; set; }
        public Nullable<System.Guid> ID_QuocGia { get; set; }
        public Nullable<int> ID_TrangThai { get; set; }
        public Nullable<System.DateTime> NgaySuaTrangThai { get; set; }
        public string TenKhac { get; set; }
        public string DiaChiKhac { get; set; }
        public Nullable<System.DateTime> NgayGiaoDichGanNhat { get; set; }
        public Nullable<System.Guid> ID_NhomCu { get; set; }
        public string TenNguonKhach { get; set; }
        public string TenNhom { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
    
        public virtual ICollection<BH_DonBanHang> BH_DonBanHang { get; set; }
        public virtual ICollection<BH_DonMuaHang> BH_DonMuaHang { get; set; }
        public virtual ICollection<BH_MuaHang> BH_MuaHang { get; set; }
        public virtual ICollection<CongNoDauKi> CongNoDauKis { get; set; }
        public virtual DM_NhomDoiTuong DM_NhomDoiTuong { get; set; }
        public virtual ICollection<DM_HangHoa> DM_HangHoa { get; set; }
        public virtual ICollection<DM_LienHe> DM_LienHe { get; set; }
        public virtual ICollection<HangDoiTraLai> HangDoiTraLais { get; set; }
        public virtual ICollection<HangTraLaiNhaCungCap> HangTraLaiNhaCungCaps { get; set; }
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
        public virtual ICollection<HoaDonBanLe> HoaDonBanLes { get; set; }
        public virtual ICollection<KH_Anh> KH_Anh { get; set; }
        public virtual ICollection<KH_NhapKho> KH_NhapKho { get; set; }
        public virtual ICollection<KH_XuatKho> KH_XuatKho { get; set; }
        public virtual ICollection<PhieuChiChiTiet> PhieuChiChiTiets { get; set; }
        public virtual ICollection<PhieuThuChiTiet> PhieuThuChiTiets { get; set; }
        public virtual ICollection<TheKhachHang> TheKhachHangs { get; set; }
        public virtual ICollection<TinNhan> TinNhans { get; set; }
    }
}
