//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GiaBan_ChiTiet
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_GiaBan { get; set; }
        public System.Guid ID_HangHoa { get; set; }
        public System.Guid ID_DonViTinh { get; set; }
        public System.Guid ID_KhoHang { get; set; }
        public double GiaBan { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public double TyGia { get; set; }
        public Nullable<int> PhuongThucTinhGiaBan { get; set; }
        public Nullable<bool> TheoPT { get; set; }
    
        public virtual DM_GiaBan DM_GiaBan { get; set; }
        public virtual DM_HangHoa DM_HangHoa { get; set; }
        public virtual DM_Kho DM_Kho { get; set; }
    }
}
