//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GiaBan
    {
        public DM_GiaBan()
        {
            this.DM_GiaBan_ChiTiet = new HashSet<DM_GiaBan_ChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaGiaBan { get; set; }
        public string TenGiaBan { get; set; }
        public bool ApDung { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string NgayTrongTuan { get; set; }
        public bool ApDungKhungGio { get; set; }
        public Nullable<System.DateTime> TuGio { get; set; }
        public Nullable<System.DateTime> DenGio { get; set; }
        public string ChungTu { get; set; }
        public Nullable<bool> GiamGiaTheoNhomDoiTuong { get; set; }
        public string ID_NhomDoiTuongs { get; set; }
        public Nullable<bool> GiamGiaTatCaDoiTuong { get; set; }
        public string ID_DoiTuongs { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public string UserLap { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string UserSua { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual ICollection<DM_GiaBan_ChiTiet> DM_GiaBan_ChiTiet { get; set; }
    }
}
