//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HangHoa
    {
        public DM_HangHoa()
        {
            this.BH_DonBanHang_ChiTiet = new HashSet<BH_DonBanHang_ChiTiet>();
            this.BH_DonMuaHang_ChiTiet = new HashSet<BH_DonMuaHang_ChiTiet>();
            this.BH_MuaHang_ChiTiet = new HashSet<BH_MuaHang_ChiTiet>();
            this.ChietKhauMacDinh_NhanVien = new HashSet<ChietKhauMacDinh_NhanVien>();
            this.DieuChuyenKho_ChiTiet = new HashSet<DieuChuyenKho_ChiTiet>();
            this.DM_GiaBan_ChiTiet = new HashSet<DM_GiaBan_ChiTiet>();
            this.DM_LoHang = new HashSet<DM_LoHang>();
            this.DM_MaVach = new HashSet<DM_MaVach>();
            this.DonViQuiDois = new HashSet<DonViQuiDoi>();
            this.HangDoiTraLaiChiTiets = new HashSet<HangDoiTraLaiChiTiet>();
            this.HangTraLaiNCCChiTiets = new HashSet<HangTraLaiNCCChiTiet>();
            this.HoaDonBanChiTiets = new HashSet<HoaDonBanChiTiet>();
            this.HoaDonBanLeChiTiets = new HashSet<HoaDonBanLeChiTiet>();
            this.KH_KiemKeChiTiet = new HashSet<KH_KiemKeChiTiet>();
            this.KH_NhapKho_ChiTiet = new HashSet<KH_NhapKho_ChiTiet>();
            this.KH_XuatKho_ChiTiet = new HashSet<KH_XuatKho_ChiTiet>();
            this.NhanVienThucHiens = new HashSet<NhanVienThucHien>();
            this.TonKhoKhoiTaos = new HashSet<TonKhoKhoiTao>();
            this.TonToiThieux = new HashSet<TonToiThieu>();
            this.ViTriHangTrongKhoes = new HashSet<ViTriHangTrongKho>();
        }
    
        public System.Guid ID { get; set; }
        public byte[] Anh { get; set; }
        public string MaHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public bool LaHangHoa { get; set; }
        public Nullable<System.Guid> ID_NhomHang { get; set; }
        public Nullable<System.Guid> ID_PhanLoai { get; set; }
        public System.Guid ID_DonViTinh { get; set; }
        public Nullable<System.Guid> ID_QuocGia { get; set; }
        public Nullable<System.Guid> ID_DoiTuong { get; set; }
        public double GiaBanLe { get; set; }
        public Nullable<System.Guid> ID_ThueSuatBan { get; set; }
        public Nullable<double> TiSuatBanLe { get; set; }
        public double GiaNhap { get; set; }
        public Nullable<System.Guid> ID_ThueSuatNhap { get; set; }
        public Nullable<double> GiaBan1 { get; set; }
        public Nullable<int> TiSuatTheoGiaBan1 { get; set; }
        public Nullable<double> GiaBan2 { get; set; }
        public Nullable<int> TiSuatTheoGiaBan2 { get; set; }
        public Nullable<double> GiaBan3 { get; set; }
        public Nullable<int> TiSuatTheoGiaBan3 { get; set; }
        public string IDs_NhomKH1 { get; set; }
        public string IDs_NhomKH2 { get; set; }
        public string IDs_NhomKH3 { get; set; }
        public string MaVach { get; set; }
        public Nullable<double> QuyCach { get; set; }
        public Nullable<System.Guid> ID_DVTQuyCach { get; set; }
        public Nullable<int> LoaiBaoHanh { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
        public string TenTGBaoHanh { get; set; }
        public double ChiPhiThucHien { get; set; }
        public bool ChiPhiTinhTheoPT { get; set; }
        public Nullable<bool> TinhCPSauChietKhau { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoPhutThucHien { get; set; }
        public Nullable<double> ChietKhauMD_NV { get; set; }
        public Nullable<bool> ChietKhauMD_NVTheoPT { get; set; }
        public Nullable<System.Guid> ID_DonViTinhPhu1 { get; set; }
        public Nullable<double> TyLeChuyenDoi1 { get; set; }
        public Nullable<System.Guid> ID_DonViTinhPhu2 { get; set; }
        public Nullable<double> TyLeChuyenDoi2 { get; set; }
        public Nullable<System.Guid> ID_DonViTinhPhu3 { get; set; }
        public Nullable<double> TyLeChuyenDoi3 { get; set; }
        public Nullable<int> TinhGiaVon { get; set; }
        public bool TheoDoi { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public string TenKhac { get; set; }
        public string ChatLieu { get; set; }
        public string KichCo { get; set; }
        public string MauSac { get; set; }
        public Nullable<double> TiSuat1 { get; set; }
        public Nullable<double> TiSuat2 { get; set; }
        public Nullable<double> TiSuat3 { get; set; }
    
        public virtual ICollection<BH_DonBanHang_ChiTiet> BH_DonBanHang_ChiTiet { get; set; }
        public virtual ICollection<BH_DonMuaHang_ChiTiet> BH_DonMuaHang_ChiTiet { get; set; }
        public virtual ICollection<BH_MuaHang_ChiTiet> BH_MuaHang_ChiTiet { get; set; }
        public virtual ICollection<ChietKhauMacDinh_NhanVien> ChietKhauMacDinh_NhanVien { get; set; }
        public virtual ICollection<DieuChuyenKho_ChiTiet> DieuChuyenKho_ChiTiet { get; set; }
        public virtual DM_DoiTuong DM_DoiTuong { get; set; }
        public virtual DM_DonViTinh DM_DonViTinh { get; set; }
        public virtual ICollection<DM_GiaBan_ChiTiet> DM_GiaBan_ChiTiet { get; set; }
        public virtual DM_NhomHangHoa DM_NhomHangHoa { get; set; }
        public virtual DM_QuocGia DM_QuocGia { get; set; }
        public virtual DM_ThueSuat DM_ThueSuat { get; set; }
        public virtual DM_ThueSuat DM_ThueSuat1 { get; set; }
        public virtual ICollection<DM_LoHang> DM_LoHang { get; set; }
        public virtual ICollection<DM_MaVach> DM_MaVach { get; set; }
        public virtual ICollection<DonViQuiDoi> DonViQuiDois { get; set; }
        public virtual ICollection<HangDoiTraLaiChiTiet> HangDoiTraLaiChiTiets { get; set; }
        public virtual ICollection<HangTraLaiNCCChiTiet> HangTraLaiNCCChiTiets { get; set; }
        public virtual ICollection<HoaDonBanChiTiet> HoaDonBanChiTiets { get; set; }
        public virtual ICollection<HoaDonBanLeChiTiet> HoaDonBanLeChiTiets { get; set; }
        public virtual ICollection<KH_KiemKeChiTiet> KH_KiemKeChiTiet { get; set; }
        public virtual ICollection<KH_NhapKho_ChiTiet> KH_NhapKho_ChiTiet { get; set; }
        public virtual ICollection<KH_XuatKho_ChiTiet> KH_XuatKho_ChiTiet { get; set; }
        public virtual ICollection<NhanVienThucHien> NhanVienThucHiens { get; set; }
        public virtual ICollection<TonKhoKhoiTao> TonKhoKhoiTaos { get; set; }
        public virtual ICollection<TonToiThieu> TonToiThieux { get; set; }
        public virtual ICollection<ViTriHangTrongKho> ViTriHangTrongKhoes { get; set; }
    }
}
