//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KhuyenMai
    {
        public DM_KhuyenMai()
        {
            this.DM_KhuyenMai_ChiTiet = new HashSet<DM_KhuyenMai_ChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<bool> GiamGiaTheoNhomDoiTuong { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string NgayTrongTuan { get; set; }
        public string ChungTu { get; set; }
        public Nullable<System.DateTime> DenGio { get; set; }
        public Nullable<bool> GiamGiaTatCaDoiTuong { get; set; }
        public string ID_DoiTuongs { get; set; }
        public string ID_NhomDoiTuongs { get; set; }
        public string MaKhuyenMai { get; set; }
        public string TenKhuyenMai { get; set; }
        public Nullable<System.DateTime> TuGio { get; set; }
        public bool ApDung { get; set; }
        public bool ApDungKhungGio { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
    
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual ICollection<DM_KhuyenMai_ChiTiet> DM_KhuyenMai_ChiTiet { get; set; }
    }
}
