//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LoaiPhong
    {
        public System.Guid ID { get; set; }
        public string MaLoai { get; set; }
        public string TenLoai { get; set; }
        public Nullable<int> SoNguoi_Min { get; set; }
        public Nullable<int> SoNguoi_Max { get; set; }
        public bool SuDung { get; set; }
        public Nullable<int> MauSac { get; set; }
        public string UserNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string UserSua { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    }
}
