//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LoHang
    {
        public DM_LoHang()
        {
            this.BH_DonBanHang_ChiTiet = new HashSet<BH_DonBanHang_ChiTiet>();
            this.BH_DonMuaHang_ChiTiet = new HashSet<BH_DonMuaHang_ChiTiet>();
            this.BH_MuaHang_ChiTiet = new HashSet<BH_MuaHang_ChiTiet>();
            this.DieuChuyenKho_ChiTiet = new HashSet<DieuChuyenKho_ChiTiet>();
            this.HangDoiTraLaiChiTiets = new HashSet<HangDoiTraLaiChiTiet>();
            this.HangTraLaiNCCChiTiets = new HashSet<HangTraLaiNCCChiTiet>();
            this.HoaDonBanChiTiets = new HashSet<HoaDonBanChiTiet>();
            this.HoaDonBanLeChiTiets = new HashSet<HoaDonBanLeChiTiet>();
            this.KH_KiemKeChiTiet = new HashSet<KH_KiemKeChiTiet>();
            this.KH_NhapKho_ChiTiet = new HashSet<KH_NhapKho_ChiTiet>();
            this.KH_XuatKho_ChiTiet = new HashSet<KH_XuatKho_ChiTiet>();
            this.TonKhoKhoiTaos = new HashSet<TonKhoKhoiTao>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ID_HangHoa { get; set; }
        public string SoLo { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
        public string TenLo { get; set; }
    
        public virtual ICollection<BH_DonBanHang_ChiTiet> BH_DonBanHang_ChiTiet { get; set; }
        public virtual ICollection<BH_DonMuaHang_ChiTiet> BH_DonMuaHang_ChiTiet { get; set; }
        public virtual ICollection<BH_MuaHang_ChiTiet> BH_MuaHang_ChiTiet { get; set; }
        public virtual ICollection<DieuChuyenKho_ChiTiet> DieuChuyenKho_ChiTiet { get; set; }
        public virtual DM_HangHoa DM_HangHoa { get; set; }
        public virtual ICollection<HangDoiTraLaiChiTiet> HangDoiTraLaiChiTiets { get; set; }
        public virtual ICollection<HangTraLaiNCCChiTiet> HangTraLaiNCCChiTiets { get; set; }
        public virtual ICollection<HoaDonBanChiTiet> HoaDonBanChiTiets { get; set; }
        public virtual ICollection<HoaDonBanLeChiTiet> HoaDonBanLeChiTiets { get; set; }
        public virtual ICollection<KH_KiemKeChiTiet> KH_KiemKeChiTiet { get; set; }
        public virtual ICollection<KH_NhapKho_ChiTiet> KH_NhapKho_ChiTiet { get; set; }
        public virtual ICollection<KH_XuatKho_ChiTiet> KH_XuatKho_ChiTiet { get; set; }
        public virtual ICollection<TonKhoKhoiTao> TonKhoKhoiTaos { get; set; }
    }
}
