//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LoaiGiaPhong
    {
        public System.Guid ID { get; set; }
        public string MaLoai { get; set; }
        public string TenLoai { get; set; }
        public bool LaGiaNgay { get; set; }
        public Nullable<double> ThoiGian_Min { get; set; }
        public Nullable<double> ThoiGian_Max { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> SoGioToiThieu { get; set; }
    }
}
