//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NhomDoiTuong
    {
        public DM_NhomDoiTuong()
        {
            this.DM_DoiTuong = new HashSet<DM_DoiTuong>();
        }
    
        public System.Guid ID { get; set; }
        public string MaNhom { get; set; }
        public string TenNhom { get; set; }
        public string GhiChu { get; set; }
        public int LoaiDoiTuong { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
    
        public virtual ICollection<DM_DoiTuong> DM_DoiTuong { get; set; }
    }
}
