//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NganHang
    {
        public System.Guid ID { get; set; }
        public string MaNganHang { get; set; }
        public string TenNganHang { get; set; }
        public string GhiChu { get; set; }
        public string ChiNhanh { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
        public Nullable<double> ChiPhiThanhToan { get; set; }
        public Nullable<bool> TheoPhanTram { get; set; }
        public Nullable<bool> MacDinh { get; set; }
        public Nullable<bool> ThuPhiThanhToan { get; set; }
    }
}
