//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PhanLoaiHangHoaDichVu
    {
        public System.Guid ID { get; set; }
        public string MaPhanLoai { get; set; }
        public string TenPhanLoai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
    }
}
