//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_QuocGia
    {
        public DM_QuocGia()
        {
            this.DM_HangHoa = new HashSet<DM_HangHoa>();
            this.DM_TienTe = new HashSet<DM_TienTe>();
            this.DM_TinhThanh = new HashSet<DM_TinhThanh>();
        }
    
        public System.Guid ID { get; set; }
        public string MaNuoc { get; set; }
        public string TenNuoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
    
        public virtual ICollection<DM_HangHoa> DM_HangHoa { get; set; }
        public virtual ICollection<DM_TienTe> DM_TienTe { get; set; }
        public virtual ICollection<DM_TinhThanh> DM_TinhThanh { get; set; }
    }
}
