//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ThueSuat
    {
        public DM_ThueSuat()
        {
            this.BH_DonMuaHang_ChiTiet = new HashSet<BH_DonMuaHang_ChiTiet>();
            this.BH_MuaHang_ChiTiet = new HashSet<BH_MuaHang_ChiTiet>();
            this.DM_HangHoa = new HashSet<DM_HangHoa>();
            this.DM_HangHoa1 = new HashSet<DM_HangHoa>();
            this.HangDoiTraLaiChiTiets = new HashSet<HangDoiTraLaiChiTiet>();
            this.HangTraLaiNCCChiTiets = new HashSet<HangTraLaiNCCChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaThueSuat { get; set; }
        public int ThueSuat { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
    
        public virtual ICollection<BH_DonMuaHang_ChiTiet> BH_DonMuaHang_ChiTiet { get; set; }
        public virtual ICollection<BH_MuaHang_ChiTiet> BH_MuaHang_ChiTiet { get; set; }
        public virtual ICollection<DM_HangHoa> DM_HangHoa { get; set; }
        public virtual ICollection<DM_HangHoa> DM_HangHoa1 { get; set; }
        public virtual ICollection<HangDoiTraLaiChiTiet> HangDoiTraLaiChiTiets { get; set; }
        public virtual ICollection<HangTraLaiNCCChiTiet> HangTraLaiNCCChiTiets { get; set; }
    }
}
