//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_VungMien
    {
        public DM_VungMien()
        {
            this.DM_TinhThanh = new HashSet<DM_TinhThanh>();
        }
    
        public System.Guid ID { get; set; }
        public string MaVung { get; set; }
        public string TenVung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<DM_TinhThanh> DM_TinhThanh { get; set; }
    }
}
