//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViQuiDoi
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_HangHoa { get; set; }
        public System.Guid ID_DonViTinh { get; set; }
        public double TyLeChuyenDoi { get; set; }
        public bool LaDonViChuan { get; set; }
        public double GiaNhap { get; set; }
        public double GiaBan { get; set; }
        public string GhiChu { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    
        public virtual DM_DonViTinh DM_DonViTinh { get; set; }
        public virtual DM_HangHoa DM_HangHoa { get; set; }
    }
}
