//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gara_Xe
    {
        public System.Guid ID { get; set; }
        public string BienSo { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public string DoiXe { get; set; }
        public Nullable<System.Guid> ID_LoaiXe { get; set; }
        public string MauSon { get; set; }
        public string DungTich { get; set; }
        public string HopSo { get; set; }
        public string MaNoiThat { get; set; }
        public string SoDangKy { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public string NoiDangKy { get; set; }
        public Nullable<System.Guid> ID_ChuXe { get; set; }
        public Nullable<System.Guid> ID_LienHe { get; set; }
        public Nullable<System.Guid> ID_BaoHiem { get; set; }
        public Nullable<System.Guid> ID_LienHeBaoHiem { get; set; }
        public string GhiChu { get; set; }
        public string UserLap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public byte[] Anh { get; set; }
    }
}
