//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gara_QuaTrinhSuaChua
    {
        public System.Guid ID { get; set; }
        public string MaSuaChua { get; set; }
        public System.DateTime NgayVaoXuong { get; set; }
        public System.Guid ID_Xe { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public Nullable<System.Guid> ID_LienHeChuXe { get; set; }
        public Nullable<double> KMVaoXuong { get; set; }
        public Nullable<double> KMXuatXuong { get; set; }
        public Nullable<System.DateTime> NgayXuatXuong { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public string GhiChu { get; set; }
        public bool TheoDoi { get; set; }
        public Nullable<System.Guid> ID_CoVanDichVu { get; set; }
        public bool DaXuatXuong { get; set; }
        public Nullable<System.Guid> ID_BaoHiem { get; set; }
        public Nullable<System.Guid> ID_LienHeBaoHiem { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_NVTiepNhanXe { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
        public string ListID_CoVanDichVu { get; set; }
        public Nullable<System.DateTime> NgayRaDuKien { get; set; }
        public string ListID_NhanVienKinhDoanh { get; set; }
        public Nullable<System.DateTime> NgayDuKienKetThuc { get; set; }
        public Nullable<System.DateTime> NgayDuKienSua { get; set; }
        public string YeuCauSuaChua { get; set; }
        public Nullable<System.Guid> ID_HinhThucSuaChua { get; set; }
        public string GhiChuXuatXuong { get; set; }
    }
}
