//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gara_ChietKhauSuaChua
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_QuaTrinh { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public double ChietKhauGuiThem { get; set; }
        public double ChietKhau_HopDongGoc { get; set; }
        public bool LaPT_HopDongGoc { get; set; }
        public double ChietKhau_GuiThem { get; set; }
        public bool LaPT_GuiThem { get; set; }
        public double ChiPhiKhac { get; set; }
    }
}
