//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangTraLaiNhaCungCap
    {
        public HangTraLaiNhaCungCap()
        {
            this.HangTraLaiNCCChiTiets = new HashSet<HangTraLaiNCCChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public string MaHoaDon { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_DoiTuong { get; set; }
        public Nullable<System.Guid> ID_LienHe { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public double TyGia { get; set; }
        public double TongTienHang { get; set; }
        public double TongTienThue { get; set; }
        public double TongChietKhau { get; set; }
        public double TongThanhToan { get; set; }
        public string DienGiai { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    
        public virtual DM_DoiTuong DM_DoiTuong { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_LienHe DM_LienHe { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
        public virtual ICollection<HangTraLaiNCCChiTiet> HangTraLaiNCCChiTiets { get; set; }
    }
}
