//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangDoiTraLai
    {
        public HangDoiTraLai()
        {
            this.HangDoiTraLaiChiTiets = new HashSet<HangDoiTraLaiChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaHoaDon { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_KhachHang { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public double TyGia { get; set; }
        public double TongTienHangDoi { get; set; }
        public double TongTienChietKhauDoi { get; set; }
        public double TongTienThueDoi { get; set; }
        public double TongThanhToanDoi { get; set; }
        public double TongTienHangTraLai { get; set; }
        public double TongTienChietKhauTraLai { get; set; }
        public double TongTienThueTraLai { get; set; }
        public double TongThanhToanTraLai { get; set; }
        public Nullable<double> TongTienBuChenhLech { get; set; }
        public string DaiDienKhachHang { get; set; }
        public string DienGiai { get; set; }
        public string UserLap { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<int> BanLe_HDBan { get; set; }
        public Nullable<System.Guid> ID_CTLienQuan { get; set; }
    
        public virtual DM_DoiTuong DM_DoiTuong { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
        public virtual ICollection<HangDoiTraLaiChiTiet> HangDoiTraLaiChiTiets { get; set; }
    }
}
