//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public HoaDonBan()
        {
            this.HoaDonBanChiTiets = new HashSet<HoaDonBanChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaHoaDon { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public Nullable<System.Guid> ID_DonDatHangBan { get; set; }
        public Nullable<System.Guid> ID_KhachHang { get; set; }
        public string DiaChi_KhachHang { get; set; }
        public string DienThoai_KhachHang { get; set; }
        public string Fax_KhachHang { get; set; }
        public Nullable<System.Guid> ID_LienHe { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public double TyGia { get; set; }
        public double TongTienHang { get; set; }
        public double TienChietKhau { get; set; }
        public double TongTienThue { get; set; }
        public double TongChiPhi { get; set; }
        public double TienGiamGia { get; set; }
        public double TruTuTheTichDiem { get; set; }
        public double TongThanhToan { get; set; }
        public Nullable<System.Guid> ID_HTThanhToan { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public string UserLap { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public string DienGiai { get; set; }
        public string NoiDungChiPhi { get; set; }
        public Nullable<System.Guid> ID_QuaTrinh { get; set; }
        public Nullable<bool> XuatKhoToanBo { get; set; }
    
        public virtual BH_DonBanHang BH_DonBanHang { get; set; }
        public virtual DM_DoiTuong DM_DoiTuong { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_LienHe DM_LienHe { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
        public virtual ICollection<HoaDonBanChiTiet> HoaDonBanChiTiets { get; set; }
    }
}
