//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBanLeChiTiet
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_HoaDon { get; set; }
        public System.Guid ID_HangHoa { get; set; }
        public Nullable<System.Guid> ID_KhoHang { get; set; }
        public System.Guid ID_DonViTinh { get; set; }
        public Nullable<System.Guid> ID_LoHang { get; set; }
        public double SoLuong { get; set; }
        public double DonGia { get; set; }
        public double ThanhTien { get; set; }
        public double TienChietKhau { get; set; }
        public double ThanhToan { get; set; }
        public int SoThuTu { get; set; }
        public Nullable<System.Guid> ID_ThueSuat { get; set; }
        public double TienThue { get; set; }
        public string ChatLieu { get; set; }
        public string MauSac { get; set; }
        public string KichCo { get; set; }
        public Nullable<double> GiaVon { get; set; }
        public Nullable<System.Guid> ID_MaVach { get; set; }
        public double PTChietKhau { get; set; }
        public double PTChiPhi { get; set; }
        public double TienChiPhi { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> LoaiThoiGianBH { get; set; }
        public Nullable<double> ThoiGianBaoHanh { get; set; }
        public string GhiChu { get; set; }
        public string UserNhap { get; set; }
        public Nullable<double> SoLanDaIn { get; set; }
        public Nullable<System.Guid> ID_TangKem { get; set; }
        public Nullable<bool> TangKem { get; set; }
        public Nullable<double> ThoiGianThucHien { get; set; }
        public Nullable<double> SoLuong_TL { get; set; }
        public Nullable<double> SoLuong_YC { get; set; }
        public Nullable<bool> Chieu { get; set; }
        public Nullable<bool> Sang { get; set; }
        public Nullable<double> PTThue { get; set; }
    
        public virtual DM_DonViTinh DM_DonViTinh { get; set; }
        public virtual DM_HangHoa DM_HangHoa { get; set; }
        public virtual DM_Kho DM_Kho { get; set; }
        public virtual DM_LoHang DM_LoHang { get; set; }
        public virtual HoaDonBanLe HoaDonBanLe { get; set; }
    }
}
