//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBanLe
    {
        public HoaDonBanLe()
        {
            this.HoaDonBanLeChiTiets = new HashSet<HoaDonBanLeChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaHoaDon { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
        public Nullable<System.Guid> ID_ViTri { get; set; }
        public Nullable<System.Guid> ID_CheckIn { get; set; }
        public System.Guid ID_DoiTuong { get; set; }
        public string DiaChi_KhachHang { get; set; }
        public string DienThoai_KhachHang { get; set; }
        public string Fax_KhachHang { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public double TyGia { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public int LoaiHoaDon { get; set; }
        public bool ChoThanhToan { get; set; }
        public double TongTienHang { get; set; }
        public double TongChietKhau { get; set; }
        public double TongTienThue { get; set; }
        public double TongGiamGia { get; set; }
        public double TongChiPhi { get; set; }
        public double PhaiThanhToan { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> SoLanIn { get; set; }
        public string UserLap { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public string UserSuaCuoi { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public string YeuCau { get; set; }
    
        public virtual DM_DoiTuong DM_DoiTuong { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
        public virtual ICollection<HoaDonBanLeChiTiet> HoaDonBanLeChiTiets { get; set; }
    }
}
