//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan_ChietKhauThanhToan
    {
        public System.Guid ID { get; set; }
        public string SoPhieu { get; set; }
        public System.DateTime Ngay { get; set; }
        public System.Guid ID_HoaDon { get; set; }
        public double ChietKhauThanhToan { get; set; }
        public bool LaPhanTram { get; set; }
    }
}
