//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDichVu
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_HoaDon { get; set; }
        public System.DateTime BDDichVu { get; set; }
        public System.DateTime KTDichVu { get; set; }
        public double TongThoiGian { get; set; }
        public double DonGiaDichVu { get; set; }
        public double TongTienDichVu { get; set; }
        public double ChietKhau { get; set; }
        public bool LaPTChietKhau { get; set; }
        public double PTThue { get; set; }
        public double TienThue { get; set; }
        public double TongThanhToan { get; set; }
        public bool DangTinhGio { get; set; }
    }
}
