//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_CheckIn
    {
        public System.Guid ID { get; set; }
        public string SoPhieu { get; set; }
        public System.DateTime NgayCheckIn { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> ID_TienTe { get; set; }
        public Nullable<double> TyGia { get; set; }
        public string UserLap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string UserSua { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.Guid> ID_Booking { get; set; }
    }
}
