//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_DonGiaPhong
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_LoaiPhong { get; set; }
        public System.Guid ID_LoaiGia { get; set; }
        public double DonGia { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    }
}
