//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRS_DonGiaViTri
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_NhomDoiTuong { get; set; }
        public System.Guid ID_ViTri { get; set; }
        public System.DateTime ThoiGian_BD { get; set; }
        public System.DateTime ThoiGian_KT { get; set; }
        public double DonGia { get; set; }
        public string GhiChu { get; set; }
    }
}
