//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_KiemKeChiTiet
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_KiemKe { get; set; }
        public Nullable<System.Guid> ID_Kho { get; set; }
        public System.Guid ID_HangHoa { get; set; }
        public System.Guid ID_DonViTinh { get; set; }
        public Nullable<System.Guid> ID_LoHang { get; set; }
        public double SoLuongTon { get; set; }
        public bool TheoLo { get; set; }
        public double SoLuongKiemKe { get; set; }
        public Nullable<System.Guid> ID_NhaCC { get; set; }
        public Nullable<System.Guid> ID_MaVach { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> GiaTri { get; set; }
    
        public virtual DM_DonViTinh DM_DonViTinh { get; set; }
        public virtual DM_HangHoa DM_HangHoa { get; set; }
        public virtual DM_Kho DM_Kho { get; set; }
        public virtual DM_LoHang DM_LoHang { get; set; }
        public virtual KH_KiemKe KH_KiemKe { get; set; }
    }
}
