//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_NhapKho
    {
        public KH_NhapKho()
        {
            this.KH_NhapKho_ChiTiet = new HashSet<KH_NhapKho_ChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string SoChungTu { get; set; }
        public System.DateTime NgayChungTu { get; set; }
        public Nullable<System.Guid> ID_DoiTuong { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public double TyGia { get; set; }
        public string NguoiGiao { get; set; }
        public Nullable<double> TongThanhTien { get; set; }
        public string DienGiai { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public Nullable<System.Guid> ID_ChungTuLienQuan { get; set; }
        public Nullable<int> LoaiChungTuLienQuan { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public string UserLap { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.Guid> ID_LoaiNhapKho { get; set; }
        public Nullable<System.Guid> ID_PhieuSuaChua { get; set; }
    
        public virtual DM_DoiTuong DM_DoiTuong { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
        public virtual ICollection<KH_NhapKho_ChiTiet> KH_NhapKho_ChiTiet { get; set; }
    }
}
