//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMaiTangKem
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ID_Kho { get; set; }
        public System.DateTime TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public bool ApDung { get; set; }
        public Nullable<bool> LaKhuyenMaiThe { get; set; }
    }
}
