//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichNhacBaoHanh_XeBan
    {
        public System.Guid ID { get; set; }
        public bool ApDung { get; set; }
        public string MaBaoHanh { get; set; }
        public Nullable<System.Guid> NhomHangHoa { get; set; }
        public string UserLap { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.Guid> ID_HangHoa { get; set; }
    }
}
