//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHenKhachHang
    {
        public System.Guid ID { get; set; }
        public string TieuDe { get; set; }
        public System.DateTime NgayDatLich { get; set; }
        public System.DateTime NgayHen { get; set; }
        public bool CaNgay { get; set; }
        public System.DateTime ThoiGianTu { get; set; }
        public System.DateTime ThoiGianDen { get; set; }
        public Nullable<System.Guid> ID_KhachHang { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> LoaiLichHen { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public bool NhacNho { get; set; }
        public double NhacNhoTruoc { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string CongViec { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> ID_DichVu { get; set; }
        public string DienThoai { get; set; }
        public Nullable<bool> NhacNgay { get; set; }
        public Nullable<System.Guid> ID_PhanLoai { get; set; }
        public Nullable<System.Guid> ID_LienHe { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public Nullable<System.Guid> ID_ViTri { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<System.Guid> ID_LoaiLyDoHuy { get; set; }
        public Nullable<System.Guid> ID_NoiDungQuanTam { get; set; }
        public Nullable<System.Guid> ID_TuVan { get; set; }
        public string LyDoHuyLichHen { get; set; }
        public string NguonKhach { get; set; }
        public string NhanVienLienQuan { get; set; }
        public string NoiDungQuanTam { get; set; }
        public Nullable<bool> LaLichHen { get; set; }
        public Nullable<bool> TheoDoi { get; set; }
    }
}
