//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoHinhKhuVuc
    {
        public System.Guid ID { get; set; }
        public string TenMoHinh { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public double TyLeChieuCao { get; set; }
        public double TyLeChieuRong { get; set; }
        public bool LaGroup { get; set; }
        public Nullable<System.Guid> ID_Parent { get; set; }
        public System.Guid IDKhuVuc { get; set; }
        public Nullable<System.Guid> ID_Tag { get; set; }
        public byte[] Anh { get; set; }
        public double TyLeX { get; set; }
        public double TyLeY { get; set; }
    }
}
