//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAnChoThucHien
    {
        public System.Guid ID { get; set; }
        public System.Guid MonAn { get; set; }
        public Nullable<System.Guid> BanAn { get; set; }
        public int SoLuong { get; set; }
        public System.Guid CTHD { get; set; }
        public Nullable<System.Guid> HD { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> DaXong { get; set; }
        public Nullable<bool> DangLam { get; set; }
        public Nullable<bool> Huy { get; set; }
        public string GhiChu { get; set; }
    }
}
