//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu_ChungTuChiTiet
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_ChungTu { get; set; }
        public System.Guid ID_ChungTuChiTiet { get; set; }
        public int LoaiChungTu { get; set; }
        public System.Guid ID_HangHoaDichVu { get; set; }
        public double SoLuong { get; set; }
        public System.Guid ID_DonViTinh { get; set; }
        public System.Guid ID_Kho { get; set; }
        public Nullable<System.Guid> ID_LoHang { get; set; }
        public string MaVach { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> ID_KhoNhap { get; set; }
        public Nullable<double> DonGia { get; set; }
    }
}
