//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienTuVan
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_NhanVien { get; set; }
        public int LoaiChungTu { get; set; }
        public System.Guid ID_ChungTu { get; set; }
        public Nullable<System.Guid> ID_ChungTuChiTiet { get; set; }
        public double TienChietKhau { get; set; }
        public bool LaPhanTram { get; set; }
        public Nullable<bool> ChietKhauTheoThucThu { get; set; }
        public Nullable<double> PTDoanhThuDuocHuong { get; set; }
        public string DienGiai { get; set; }
    
        public virtual DM_NhanVien DM_NhanVien { get; set; }
    }
}
