//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienThucHien
    {
        public System.Guid ID { get; set; }
        public int LoaiChungTu { get; set; }
        public System.Guid MaChungTu { get; set; }
        public System.Guid NhanVien { get; set; }
        public Nullable<System.Guid> ID_ChiTietChungTu { get; set; }
        public Nullable<System.Guid> ID_CongViec { get; set; }
        public double TienChietKhau { get; set; }
        public bool LaPhanTram { get; set; }
        public bool LaNhanVienChinh { get; set; }
        public string DienGiai { get; set; }
        public Nullable<System.Guid> ID_NhanVienChinh { get; set; }
        public Nullable<bool> ChietKhauTheoThucThu { get; set; }
        public Nullable<double> PTDoanhThuDuocHuong { get; set; }
        public Nullable<bool> DuocYeuCau { get; set; }
        public Nullable<double> ChiPhiThucHien { get; set; }
        public Nullable<bool> LaPTChiPhiThucHien { get; set; }
    
        public virtual DM_HangHoa DM_HangHoa { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
    }
}
