//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyThayDoiNhomKhachHang
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public System.DateTime NgayThayDoiNhom { get; set; }
        public Nullable<System.Guid> ID_NhomCu { get; set; }
        public System.Guid ID_NhomMoi { get; set; }
    }
}
