//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyBaoHanh_NhomHH_HangHoa
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_HangHoa { get; set; }
        public System.DateTime ThoiGianBaoHanh { get; set; }
        public Nullable<System.Guid> ID_NhanVienBaoHanh { get; set; }
        public string GhiChu { get; set; }
        public System.Guid ID_DonVi { get; set; }
    }
}
