//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKySuDung_PhieuThanhToan
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_PhieuThanhToan { get; set; }
        public int LoaiChungTu { get; set; }
        public System.Guid ID_ChungTu { get; set; }
        public double SoTienThanhToan { get; set; }
        public System.DateTime NgaySuDung { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public string UserName { get; set; }
    }
}
