//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_ChamCong_ChiTiet
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_NhanVien { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public string Ngay1 { get; set; }
        public string Ngay2 { get; set; }
        public string Ngay3 { get; set; }
        public string Ngay4 { get; set; }
        public string Ngay5 { get; set; }
        public string Ngay6 { get; set; }
        public string Ngay7 { get; set; }
        public string Ngay8 { get; set; }
        public string Ngay9 { get; set; }
        public string Ngay10 { get; set; }
        public string Ngay11 { get; set; }
        public string Ngay12 { get; set; }
        public string Ngay13 { get; set; }
        public string Ngay14 { get; set; }
        public string Ngay15 { get; set; }
        public string Ngay16 { get; set; }
        public string Ngay17 { get; set; }
        public string Ngay18 { get; set; }
        public string Ngay19 { get; set; }
        public string Ngay20 { get; set; }
        public string Ngay21 { get; set; }
        public string Ngay22 { get; set; }
        public string Ngay23 { get; set; }
        public string Ngay24 { get; set; }
        public string Ngay25 { get; set; }
        public string Ngay26 { get; set; }
        public string Ngay27 { get; set; }
        public string Ngay28 { get; set; }
        public string Ngay29 { get; set; }
        public string Ngay30 { get; set; }
        public string Ngay31 { get; set; }
        public double SoNgayNghi { get; set; }
        public double TongCong { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    
        public virtual DM_NhanVien DM_NhanVien { get; set; }
    }
}
