//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_QuaTrinhCongTac
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_NhanVien { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public Nullable<System.Guid> ID_ChucVu { get; set; }
        public System.DateTime NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public bool LaChucVuHienThoi { get; set; }
        public bool LaDonViHienThoi { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public string UserLap { get; set; }
        public string UserSuaCuoi { get; set; }
    
        public virtual DM_ChucVu DM_ChucVu { get; set; }
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
    }
}
