//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoiKhachHang
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public Nullable<System.DateTime> NgayLienHe { get; set; }
        public Nullable<System.Guid> ID_LienHe { get; set; }
        public Nullable<System.Guid> ID_Xe { get; set; }
        public Nullable<System.Guid> ID_NhanVienNhan { get; set; }
        public Nullable<System.Guid> ID_NhanVienTraLoi { get; set; }
        public Nullable<System.Guid> ID_PhanLoai { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string NoiDungTraLoi { get; set; }
        public string UserLap { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string UserSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string ID_DonVis { get; set; }
        public string ID_NhanViens { get; set; }
        public string KetQua { get; set; }
        public Nullable<int> MucDoDanhGia { get; set; }
        public Nullable<int> MucDoPhanHoi { get; set; }
        public Nullable<System.Guid> ID_DichVu { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
