//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public PhieuThu()
        {
            this.PhieuThuChiTiets = new HashSet<PhieuThuChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaPhieuThu { get; set; }
        public System.DateTime NgayLapPhieu { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_NgoaiTe { get; set; }
        public string NguoiNopTien { get; set; }
        public string NoiDungThu { get; set; }
        public double TongTienThu { get; set; }
        public bool ThuCuaNhieuDoiTuong { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public double TyGia { get; set; }
        public string UserLap { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.Guid> ID_DoiTuong { get; set; }
    
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_NhanVien DM_NhanVien { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
        public virtual ICollection<PhieuThuChiTiet> PhieuThuChiTiets { get; set; }
    }
}
