//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThanhToan
    {
        public System.Guid ID { get; set; }
        public string MaThe { get; set; }
        public string TenThe { get; set; }
        public System.DateTime NgaySuDung { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public double MenhGia { get; set; }
        public System.Guid ID_TienTe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> ID_LoaiPhieu { get; set; }
        public Nullable<double> SoLanSuDung { get; set; }
    }
}
