//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenMacDinh
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<bool> NhapGiaBan { get; set; }
        public Nullable<bool> NhapChietKhau { get; set; }
        public Nullable<System.Guid> IDDoiTuong_HBTL { get; set; }
        public Nullable<System.Guid> IDDoiTuong_HDB { get; set; }
        public Nullable<System.Guid> IDDoiTuong_HDBL { get; set; }
        public Nullable<System.Guid> IDDoiTuong_MuaHang { get; set; }
        public Nullable<System.Guid> IDDoiTuong_NhapKho { get; set; }
        public Nullable<System.Guid> IDDoiTuong_PhieuChi { get; set; }
        public Nullable<System.Guid> IDDoiTuong_PhieuThu { get; set; }
        public Nullable<System.Guid> IDDoiTuong_TraLaiNCC { get; set; }
        public Nullable<System.Guid> IDDoiTuong_XuatKho { get; set; }
        public Nullable<System.Guid> IDKho_DieuChuyen { get; set; }
        public Nullable<System.Guid> IDKho_HBTL { get; set; }
        public Nullable<System.Guid> IDKho_HDB { get; set; }
        public Nullable<System.Guid> IDKho_HDBL { get; set; }
        public Nullable<System.Guid> IDKho_MuaHang { get; set; }
        public Nullable<System.Guid> IDKho_NhapKho { get; set; }
        public Nullable<System.Guid> IDKho_TraLaiNCC { get; set; }
        public Nullable<System.Guid> IDKho_XuatKho { get; set; }
        public Nullable<bool> SuaNgayChungTu { get; set; }
        public Nullable<bool> SuaSoChungTu { get; set; }
        public Nullable<bool> ThayDoiNhanVien { get; set; }
        public Nullable<System.Guid> ID_NhomDichVu { get; set; }
        public Nullable<System.Guid> ID_NhomDoiTuong { get; set; }
        public Nullable<System.Guid> ID_NhomHangHoa { get; set; }
        public Nullable<bool> NhapChietKhauChung { get; set; }
        public Nullable<bool> NhapGiamGia { get; set; }
        public Nullable<System.Guid> IDDoiTuong_BaoGia { get; set; }
        public Nullable<System.Guid> IDDoiTuong_DonDatMua { get; set; }
        public Nullable<System.Guid> IDKho_BaoGia { get; set; }
        public Nullable<System.Guid> IDKho_DonDatMua { get; set; }
    
        public virtual sys_NguoiDung sys_NguoiDung { get; set; }
    }
}
