//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoDuKhoiTao
    {
        public System.Guid ID { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public int NamHachToan { get; set; }
        public double SoDuNo { get; set; }
        public double SoDuCo { get; set; }
        public Nullable<System.Guid> ID_TienTe { get; set; }
        public double TyGia { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    }
}
