//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDiemTich
    {
        public System.Guid ID { get; set; }
        public Nullable<int> LoaiChungTu { get; set; }
        public System.Guid ID_ChungTu { get; set; }
        public System.DateTime NgayChungTu { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public double SoTienSuDung { get; set; }
        public double SoDiemSuDung { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_PhieuThu { get; set; }
        public Nullable<System.Guid> ID_PhieuThuChiTiet { get; set; }
    }
}
