//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_NhatKyNguoiDung
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string SuKien { get; set; }
        public string ChucNang { get; set; }
        public Nullable<System.Guid> IDBanGhi { get; set; }
        public string MaBanGhi { get; set; }
        public string TenBanGhi { get; set; }
        public Nullable<System.DateTime> NgayGio { get; set; }
    
        public virtual sys_NguoiDung sys_NguoiDung { get; set; }
    }
}
