//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_NguoiDung
    {
        public sys_NguoiDung()
        {
            this.QuyenMacDinhs = new HashSet<QuyenMacDinh>();
            this.sys_NguoiDungNhom = new HashSet<sys_NguoiDungNhom>();
            this.sys_NhatKyNguoiDung = new HashSet<sys_NhatKyNguoiDung>();
            this.TaiKhoanNhanTins = new HashSet<TaiKhoanNhanTin>();
            this.TinNhans = new HashSet<TinNhan>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MoTa { get; set; }
        public string SoChungMinh { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string DienThoaiNoiLamViec { get; set; }
        public string DienThoaiNhaRieng { get; set; }
        public string DienThoaiDiDong { get; set; }
        public string Fax { get; set; }
        public string DiaChiLamViec { get; set; }
        public string NguyenQuan { get; set; }
        public string ThuongTru { get; set; }
        public string TamTru { get; set; }
        public byte[] Anh { get; set; }
        public bool LaNhanVien { get; set; }
        public bool LaAdmin { get; set; }
        public bool Inactive { get; set; }
        public bool IsSystem { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
    
        public virtual ICollection<QuyenMacDinh> QuyenMacDinhs { get; set; }
        public virtual ICollection<sys_NguoiDungNhom> sys_NguoiDungNhom { get; set; }
        public virtual ICollection<sys_NhatKyNguoiDung> sys_NhatKyNguoiDung { get; set; }
        public virtual ICollection<TaiKhoanNhanTin> TaiKhoanNhanTins { get; set; }
        public virtual ICollection<TinNhan> TinNhans { get; set; }
    }
}
