//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Company
    {
        public System.Guid ID { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string SoFax { get; set; }
        public string MaSoThue { get; set; }
        public string Mail { get; set; }
        public string Website { get; set; }
        public string TenGiamDoc { get; set; }
        public string TenKeToanTruong { get; set; }
        public byte[] Logo { get; set; }
        public string GhiChu { get; set; }
        public string TaiKhoanNganHang { get; set; }
        public string DiaChiNganHang { get; set; }
        public string TenVT { get; set; }
        public string DiaChiVT { get; set; }
        public Nullable<bool> DangHoatDong { get; set; }
    }
}
