//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_NhomNguoiDung
    {
        public sys_NhomNguoiDung()
        {
            this.sys_NguoiDungNhom = new HashSet<sys_NguoiDungNhom>();
            this.sys_QuyenNhom = new HashSet<sys_QuyenNhom>();
        }
    
        public System.Guid ID { get; set; }
        public string MaNhom { get; set; }
        public string TenNhom { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
    
        public virtual ICollection<sys_NguoiDungNhom> sys_NguoiDungNhom { get; set; }
        public virtual ICollection<sys_QuyenNhom> sys_QuyenNhom { get; set; }
    }
}
