//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_QuyenNhom
    {
        public System.Guid ID { get; set; }
        public System.Guid IDNhom { get; set; }
        public string MaQuyen { get; set; }
    
        public virtual sys_NhomNguoiDung sys_NhomNguoiDung { get; set; }
        public virtual sys_Quyen sys_Quyen { get; set; }
    }
}
