//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ID_DoiTuong { get; set; }
        public string TieuDe { get; set; }
        public System.Guid ID_PhanLoai { get; set; }
        public bool TaiLieuDen { get; set; }
        public string MoTa { get; set; }
        public string FilePath { get; set; }
        public string NguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
    }
}
