//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TangGiaTriThe
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_TheKH { get; set; }
        public System.DateTime NgayTangGT { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public Nullable<System.Guid> ID_NVLap { get; set; }
        public string MaTangGT { get; set; }
        public double DonGia { get; set; }
        public Nullable<double> PTTangThem { get; set; }
        public Nullable<double> TienTangThem { get; set; }
        public bool LaPT { get; set; }
        public double ChietKhau { get; set; }
        public double PhaiThanhToan { get; set; }
        public Nullable<System.Guid> ID_TienTe { get; set; }
        public Nullable<double> TyGia { get; set; }
        public string GhiChu { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
