//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTinNhanSM
    {
        public System.Guid ID { get; set; }
        public string ThueBaoNhan { get; set; }
        public string TBNhanTC { get; set; }
        public string TBNhanKTC { get; set; }
        public string NoiDungTN { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public bool LaTinGuiDi { get; set; }
        public bool LaTinNhap { get; set; }
        public Nullable<bool> DanhDauChuaDoc { get; set; }
        public string SoThueBaoGuiDi { get; set; }
        public string SoThueBaoGuiDen { get; set; }
        public string GhiChu { get; set; }
        public string MaTN { get; set; }
    }
}
