//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheKhachHang
    {
        public TheKhachHang()
        {
            this.NhatKySuDungThes = new HashSet<NhatKySuDungThe>();
            this.TheKhachHangChiTiets = new HashSet<TheKhachHangChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaThe { get; set; }
        public System.Guid ID_NhomThe { get; set; }
        public System.DateTime NgayMua { get; set; }
        public System.DateTime NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public double MenhGiaThe { get; set; }
        public Nullable<double> PTChietKhau { get; set; }
        public Nullable<double> TienChietKhau { get; set; }
        public double PhaiThanhToan { get; set; }
        public Nullable<System.Guid> ID_TienTe { get; set; }
        public Nullable<double> TyGia { get; set; }
        public Nullable<System.Guid> ID_NhanVienLap { get; set; }
        public bool ApDungTatCaSanPham { get; set; }
        public bool DuocChoMuon { get; set; }
        public int TheGiaTri_SoLan_GiamGia { get; set; }
        public string UserTao { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public Nullable<double> PTTangThem { get; set; }
        public Nullable<double> TienTangThem { get; set; }
        public Nullable<System.Guid> ID_LienHe { get; set; }
        public Nullable<bool> HuyThe { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
        public Nullable<int> SoLanDuocSuDung { get; set; }
    
        public virtual DM_DoiTuong DM_DoiTuong { get; set; }
        public virtual DM_NhomThe DM_NhomThe { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
        public virtual ICollection<NhatKySuDungThe> NhatKySuDungThes { get; set; }
        public virtual ICollection<TheKhachHangChiTiet> TheKhachHangChiTiets { get; set; }
    }
}
