//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoDoiLopHoc
    {
        public System.Guid ID { get; set; }
        public string SoPhieu { get; set; }
        public System.DateTime NgayTap { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public Nullable<System.Guid> ID_TheKH { get; set; }
        public Nullable<System.Guid> ID_LopHoc { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
        public Nullable<double> CanNangHT { get; set; }
        public Nullable<double> CanNangTruoc { get; set; }
        public string GhiChu { get; set; }
    }
}
