//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongHopNhapXuat
    {
        public System.Guid ID { get; set; }
        public int LoaiChungTu { get; set; }
        public System.Guid ID_ChungTu { get; set; }
        public string MaChungTu { get; set; }
        public System.DateTime NgayChungTu { get; set; }
        public System.Guid ID_ChiTiet_ChungTu { get; set; }
        public Nullable<System.Guid> ID_DoiTuong { get; set; }
        public System.Guid ID_HangHoa { get; set; }
        public System.Guid ID_DonViTinh { get; set; }
        public System.Guid ID_Kho { get; set; }
        public Nullable<System.Guid> ID_LoHang { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> TienNhap { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> TienBan { get; set; }
        public Nullable<double> ThanhToan { get; set; }
        public Nullable<double> TienChietKhau { get; set; }
        public Nullable<double> TienThue { get; set; }
        public Nullable<double> GiaXuat { get; set; }
        public Nullable<double> SoLuongNhap { get; set; }
        public Nullable<double> SoLuongXuat { get; set; }
        public Nullable<double> TienXuat { get; set; }
        public Nullable<bool> LaNhap { get; set; }
        public Nullable<System.Guid> ID_NhanVien { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public Nullable<System.Guid> ID_MaVach { get; set; }
        public Nullable<double> ChiPhi { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public string DienGiaiChungTu { get; set; }
        public string GhiChuChiTiet { get; set; }
        public Nullable<double> SoLuongChuan { get; set; }
    }
}
