//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonQuyKhoiTao
    {
        public System.Guid ID { get; set; }
        public System.DateTime NgayChungTu { get; set; }
        public int NamHachToan { get; set; }
        public double TonQuy { get; set; }
        public Nullable<System.Guid> ID_DonVi { get; set; }
        public System.Guid ID_TienTe { get; set; }
        public Nullable<bool> LaTienMat { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public double TyGia { get; set; }
        public string UserSuaCuoi { get; set; }
        public string UserTao { get; set; }
    
        public virtual DM_DonVi DM_DonVi { get; set; }
        public virtual DM_TienTe DM_TienTe { get; set; }
    }
}
