//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuVanKhachHang
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_DonVi { get; set; }
        public System.Guid ID_NhanVien { get; set; }
        public string SoPhieu { get; set; }
        public System.DateTime NgayTuVan { get; set; }
        public System.Guid ID_KhachHang { get; set; }
        public Nullable<System.Guid> ID_DichVu { get; set; }
        public string YKienKhachHang { get; set; }
        public string NoiDungTuVan { get; set; }
        public int TrangThaiSauTuVan { get; set; }
        public string UserLap { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserSuaCuoi { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<System.Guid> ID_NoiDungQuanTam2 { get; set; }
    }
}
